#!/bin/sh

if [ ! -e $HOME/.vim/autoload/plug.vim ]; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    vim -u $HOME/.vimrc.bundles +PlugInstall! +qa
fi
